### ISSUE TITLE
Creation Date of issue is not correct shown in BCFier

### ISSUE THREAD

**Issue by StefanKraftMuM** [teocomi/BCFier#10]
In BCFier Standalone Version and in Revit Plugin 2016 I get the wrong creation Date of my issue. Have downloaded from Webpage at 17.12.2015 the BCFier Version 2.0.2.0. Create BCF-File in Solibri Model Checker with Version 2.0.
Creation Date in BCFier is shown 142 days ago 27.07.2015.
In BCF-File in the Markup.bcf the creation date is correctly: 
<CreationDate>2015-12-17T13:55:33+01:00</CreationDate>

**Comment by teocomi** [comment]
@StefanKraftMuM can you please attach the .bcfzip file so I can check? Thanks

**Comment by StefanKraftMuM** [comment]
[Präsentation.ZIP](https://github.com/teocomi/BCFier/files/73811/Prasentation.ZIP)

The date format is European (Year-Month-Day). The BCFier takes the Date and not the CreationDate. If I use another viewer as BCFManager it shows me the CreationDate and this is also the correct one, at which date I created the issue.
Do not know from which information it takes the Date.

<Header><File IfcProject="0ZM$77oyT8Nf8BoX6M41Pb">
<Filename>00001</Filename>
<Date>2015-07-27T16:18:58+02:00</Date>
</File></Header><Topic Guid="50ea67df-9d2c-4d11-b254-83878a274912" TopicType="Error" TopicStatus="Öffnen">
<Title>Wand.-1.23 (WD 20.0 LS 3.0 VS 2.0) und Wand.-2.4 (WD 12) überschneiden sich</Title>
<Index>0</Index>
<CreationDate>2015-12-17T13:55:33+01:00</CreationDate>
<CreationAuthor>sk</CreationAuthor>
<ModifiedDate>2015-12-17T13:55:33+01:00</ModifiedDate>
<ModifiedAuthor>sk</ModifiedAuthor>
<AssignedTo>ARC</AssignedTo>

**Comment by teocomi** [comment]
Implemented, will go out in the next release.
