### ISSUE TITLE
Isolating components from linked models (Revit)

### ISSUE THREAD

**Issue by alexandernesbitt** [teocomi/BCFier#13]
Hi Matteo,

I am having trouble isolating components from linked Revit files.

Scenario: Architect has linked the Structural RVT into theirs, they open the BCF and click on a viewpoint to view an issue of one of their doors hitting a Structural column, it will isolate the door but not that particular column.

Any ideas of what could be causing this issue?

Thanks,
Alex

**Comment by teocomi** [comment]
Elements of linked models are not accessible via the API so cannot be isolated :( 
Real bummer.

**Comment by alexandernesbitt** [comment]
Thanks for the reply. Can you recommend any way around this? Would the consultants have to copy models?

**Comment by teocomi** [comment]
I'm not aware of any good workaround, but sure that would work...
