### ISSUE TITLE
Issues are wrongly sorted in navigator tab

### ISSUE THREAD

**Issue by drgreb** [teocomi/BCFier#14]
We have a naming convention for issues. Basically it is the discipline which is assigned for issue and 3 digit number. 
![image](https://cloud.githubusercontent.com/assets/8932782/13075014/e294a198-d4b0-11e5-9a13-9a4923d9b06f.png)

**Comment by teocomi** [comment]
BCF does not currently have any property to preserve the sorting of the issues, as you can see from:
https://github.com/BuildingSMART/BCF-XML/issues/54

But maybe we could implement custom sorting from the BCFier UI (by date or title).

**Comment by drgreb** [comment]
Yeah, probably UI sorting would be enough, because reading new order properties from BCF file and changing them is a resource demanding feature. Also, there could be few sorting options - by name, by assigned person (), possible priority of issue etc. It all can be implemented via software, while leaving BCF file a container role.

**Comment by blecrioux** [comment]
Hello,
we're using BCFier on Revit and we have the same problem to sort issue. Since the previous post (febrary 2016), is there any update to sort issue by name or status?

**Comment by teocomi** [comment]
Hi @blecrioux unfortunately there is no timeline and I'm not expecting to be able to work on BCFier in the short term, but there might be contributions from others.

**Comment by teocomi** [comment]
@drgreb I've implemented BCF 2.1 sorting in a new beta version, please let me know if you have a chance to test it: https://github.com/teocomi/BCFier/releases/tag/2.2.0beta

**Comment by blecrioux** [comment]
Hi @teocomi 
I tested beta version 2.2.0 and it seems that sorting issues works correctly. Thank you very much! :)
A other possibility could be very interseting too: sorting issue by topic status or topic type. Do you think it's possible?

**Comment by teocomi** [comment]
@blecrioux yes definitely, will add a new feature request, but won't be able to address it in the short term...
