### ISSUE TITLE
Attached image scales with main window

### ISSUE THREAD

**Issue by drgreb** [teocomi/BCFier#16]
When you attach view to issue, view snapshot is being taken. Usually we crop it to reduce BFC file size, so it is relatively small. When you maximize BCFier window, image is scaled so you can no longer see it correctly.
![image](https://cloud.githubusercontent.com/assets/8932782/13104245/9da4d2ec-d564-11e5-9f78-ec9d6d1ef7ae.png)
![image](https://cloud.githubusercontent.com/assets/8932782/13104249/a5b0c054-d564-11e5-9150-d1b1b83c6d36.png)

**Comment by teocomi** [comment]
Actually this was done on purpose to avoid images taking all the space, users can still click on the images to see them in real size. Ideally it would have a responsive layout that changes according to the window scale...
