### ISSUE TITLE
Linked Views in Revit 2016 Don't Match Original Screen Grab

### ISSUE THREAD

**Issue by johnw153** [teocomi/BCFier#22]
When a screen grab is added to a new item in the BCF, the view coordinates are supposed to be captured so that anyone clicking on the image in BCFier when the model is open in Revit are taken to the original view. This is not happening - the view displayed in Revit when clicking the screen grab is of the whole model. This is true even if a component was selected - the only difference being that everything except the component is temporarily hidden.

Turning on the create view option in BCFier does not help. The saved views created are also of the complete model extent.

**Comment by teocomi** [comment]
Hey @johnw153 that's definitely a bug, can you please provide more details and eventually sample files?

**Comment by johnw153** [comment]
Matteo

Many thanks for the response. Hope that you had a good Easter.

I’ve uploaded a Camtasia screen recording to try and explain the issue that we are experiencing.

I will need to get permission before I can let you have copies of the project files, but I will try my best.

John Warburton
BA (hons) DipArch RIBA
Architect
Northmill Associates Limited
1 North Parade
Parsonage Gardens
Manchester
M3 2NH
T. 0161 839 4411
This email is intended for the named recipient(s) only. Information in this email is privileged, confidential, subject to copyright and may contain personal information. If you have received this message in error, please notify the sender immediately and destroy the email. Whilst all efforts are made to safeguard emails, Northmill Associates Ltd cannot guarantee that attachments are virus free or compatible with the recipient's systems and as such does not accept liability in respect of viruses or any computer problems experienced.​

**Comment by teocomi** [comment]
@johnw153 cannot see the attachment, can you upload it to github or provide a link to it? 
Does the issue happen only of that specific project or all? What version of revit?

**Comment by MichaelAUNZ** [comment]
Hi.

I have come across the same issue. 
Has this been reviewed?

**Comment by teocomi** [comment]
@johnw153  @MichaelAUNZ I need more information about this issue:
- in what type of views are you having this issue? Isometric (default 3D) or Perspective ones?
- where were the views generated? In BCFier or other software?
- what version of Revit and BCFier are you using?
- does it happen always or only a few times?
- have you tried on a "clean" new sample model?
- was the geometry generated in Revit or imported?
