### ISSUE TITLE
BCF file created in Revit -> is not visible after import Tekla

### ISSUE THREAD

**Issue by rudibeerepoot** [teocomi/BCFier#27]
A colleague created a couple of notes in Tekla BimSight and created an BCF file.
I opened the BCF file in Revit and created some reactions on the notes.
After loading the BCF file back in Tekla BimSight I didn't see any changes i made in Revit.
How is this possible?

**Comment by teocomi** [comment]
Thanks for you feedback @rudibeerepoot, what version of the software (revit/bcfier/tekla) were you using? It could be a bug in BCFier, but in my past experience I have also seen Tekla not consuming BCF files properly.

**Comment by rudibeerepoot** [comment]
Hi, i am using:
Revit 2016,
BCFier 2.0.2.0
Tekla 1.8

**Comment by teocomi** [comment]
Hi @rudibeerepoot , it seems like that could be due to a missing bcf "status". Can you please try and let me know if it temporarily solves the issue?

Also, bimsight 1.9.7 is available, you might want to update.

![image](https://cloud.githubusercontent.com/assets/2679513/16281144/d7e37350-38ba-11e6-85df-b795aebf26a5.png)

**Comment by teocomi** [comment]
Also, bimsight 1.9.7 is available, you might want to update.

**Comment by rudibeerepoot** [comment]
Hi,

I have upgraded my Tekla to version 1.9.7
After upgrading and testing i got this error:

[cid:image002.png@01D1CE10.D1FE0820]

I can stil make bcf files in Tekla, but i can’t open bcf files made in Revit in Tekla.

Greets,

Rudi Beerepoot
BIM Specialist
T (0229) 29 15 16
E r.beerepoot@schoutentechniek.nlmailto:r.beerepoot@schoutentechniek.nl

Van: Matteo Cominetti [mailto:notifications@github.com]
Verzonden: woensdag 22 juni 2016 21:50
Aan: teocomi/BCFier
CC: Rudi Beerepoot; Mention
Onderwerp: Re: [teocomi/BCFier] BCF file created in Revit -> is not visible after import Tekla (#27)

Hi @rudibeerepoothttps://github.com/rudibeerepoot , it seems like that could be due to a missing bcf "status". Can you please try and let me know if it temporarily solves the issue?

[Afbeelding verwijderd door afzender. image]https://cloud.githubusercontent.com/assets/2679513/16281144/d7e37350-38ba-11e6-85df-b795aebf26a5.png

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHubhttps://github.com/teocomi/BCFier/issues/27#issuecomment-227856727, or mute the threadhttps://github.com/notifications/unsubscribe/ATAarSUb9kwFy7jdD0uZWQ-Y8nG9tY9qks5qOZIBgaJpZM4I1SWD.

[http://www.werkenbijschouten.nl/SchoutenTechniek.jpg]
De Marowijne 47 - 1689 AR Zwaag
Postbus 20 - 1689 ZG Zwaag
T (0229) 29 15 00
F (0229) 26 18 41
E info@schoutentechniek.nl
www.schoutentechniek.nl
www.werkenbijschouten.nl

**Comment by teocomi** [comment]
Please attach the image from github as it didn't come through.

**Comment by rudibeerepoot** [comment]
![tekla error bcf import from revit](https://cloud.githubusercontent.com/assets/19929773/16336067/c2dc8ebe-3a0a-11e6-9164-67d273534644.PNG)

**Comment by teocomi** [comment]
Please provide a .bcfzip file too as I cannot replicate. Thanks

**Comment by rudibeerepoot** [comment]
In the attachment a test project with the Revit project, the IFC and the BCF file from Revit.

https://we.tl/10JDqdk4qj

**Comment by Siulum** [comment]
Hey Guys

We are testing BCF format between Tekla 2016 and Revit 2016 as well. And we have the same problems. I can see all the issues in Revit also updated issues and comments both from Tekla 2016 and Tekla BIM Sight. 
We can't see updated comments out of Revit in Tekla. 
We can attach all bcf-files from Tekla to BIM Sight. For some reason we could only attach a few bcf-files out of Revit in BIM Sight. For most cases we get the same error like rudibeer.

Kind Regards

Michael

**Comment by teocomi** [comment]
@Siulum @rudibeerepoot the only BCF statuses supported by Tekla BIMSight are: Error, Warning, Info, Unknown. If any of the comments uses a different status the import will fail. This is because Tekla only supports BCF v1 while BCFier also supports BCF v2.

Please try again and let me know.

![image](https://cloud.githubusercontent.com/assets/2679513/16895978/d6a085d4-4b7d-11e6-88cd-832e3354d1ea.png)

**Comment by Siulum** [comment]
Hi Teocomi

thx for the info. Tekla Structures uses BCF2.0 as well. TeklaBIM Sight only BCF1.0 :(

For sharing of BCF2.0 between Revit and Tekla it iis important to fill the

> Verbal Status (optional)

The Status column in Tekla is not filled when using statuses from the combobox!

Kind Regards 

Michael
