### ISSUE TITLE
Crash importing a custom BCF file

### ISSUE THREAD

**Issue by Noxalus** [teocomi/BCFier#28]
Hello,

I'm trying to import a BCF file generated from another software to Revit using this plugin, but Revit systematically crash with no error message.

Here is the file that I try to import => https://mega.nz/#!xh1hHQ5J!WM8zYTlOJAgZC7TIg0wh7dlscQNFzqPmVbgcZNo_0lQ

Do you know what is wrong with this file?

**Comment by teocomi** [comment]
Hi,
the bcf provided is not formatted correctly. It is supposed to contain some snapshots but none are included. Where was it generated? 
I've fixed the issue in BCFier and from the next version it won't crash.

![image](https://cloud.githubusercontent.com/assets/2679513/17037677/eb483ddc-4f89-11e6-93cd-05ef2794ba5c.png)

**Comment by Noxalus** [comment]
Thanks a lot for your answer! 

In fact, I'm currently writing the BCF generator that generated this file and I've tested it with DDS-CAD Viewer, in which I have no problem to load this BCF file.
