### ISSUE TITLE
BCF v2.1 changes

### ISSUE THREAD

**Issue by alexandernesbitt** [teocomi/BCFier#29]
Hi Matteo,

Just wondering if you are working through aligning with the [schema changes release in August 2016](https://github.com/BuildingSMART/BCF-XML/blob/master/ChangeLog.md)? The only major one that is effecting me is:

> Removed element "Comment/VerbalStatus". In V2.1 the status of a topic is represented only by the attrbute "Topic/TopicStatus".

Could you please update and point the VerbalStatus to TopicStatus instead?

Cheers,
Alex

**Comment by teocomi** [comment]
Hi Alex,
BCF 2.1 is still a draft so I won't be implementing the new features yet. Also, I haven't set any timeline on BCFier, but if you need any specific developments I am available for contract work.

Thanks

**Comment by alexandernesbitt** [comment]
Thanks Matteo, completely understand that this is a side project and will definitely keep in mind your availability for work.

**Comment by teocomi** [comment]
@alexandernesbitt I've implemented most of the BCF 2.1 features in a new beta version, please let me know if you have a chance to test it: https://github.com/teocomi/BCFier/releases/tag/2.2.0beta
