### ISSUE TITLE
Hiding a model when selecting issue

### ISSUE THREAD

**Issue by astanfor** [teocomi/BCFier#30]
When I select an issue from the BCF plugin window for Revit it is only showing the m&e and not the clashing structure model? is there a setting to ensure all models show?

![image](https://cloud.githubusercontent.com/assets/23194570/19922159/4b47f538-a0d9-11e6-88f9-97f99b395e9c.png)

**Comment by jsdbroughton** [comment]
Sorry to chime in as i'm not maintaining this repo, but I have some tangential information.

This has come up in discussions with the Revit API and Dynamo groupies. There is no API method to isolate elements within linked models. A workaround discussed has been that you would need to bind in the structural model into a separate Workset each time they updated it. you might then be able to get the result you want.

YMMV

**Comment by teocomi** [comment]
If it's a liked model it's exactly what @stardotbmp mentions, see also #13.
