### ISSUE TITLE
Statute of comment are not saved

### ISSUE THREAD

**Issue by JPTrehen** [teocomi/BCFier#32]
Hi,

It seems that statute and comment are not saved. Each time you reopen the file, all statutes are reinitialized to the 1rst item of the list (options)

Regards.
Great job !

**Comment by teocomi** [comment]
Hi @JPTrehen have you added the statuses manually in settings and saved the configuration or simply opened a file?

**Comment by teocomi** [comment]
Closing issue as no additional info was provided.
