### ISSUE TITLE
BCFier does not crop the view (Assistantance Needed)

### ISSUE THREAD

**Issue by shahnizammy** [teocomi/BCFier#33]
Hello, 

I installed the BCFier plugins into my Revit 2016, but it cannot crop the view in 3D view based on my BCF 2.0 file that I generate from Solibri Model Checker.

I already switch ON the Section Box in my 3D View, but end up the same problem. It just zooms to the component that contains the issues. 

But, you already created the awesome software that might can collaborate the issues among the person in-charge in a construction project. Good Job.

**Comment by teocomi** [comment]
Hi @shahnizammy, I'm not sure I understand correctly your problem. 
Are the views generated in Solibri having a different zoom inside of Revit? Is this the problem?
Can you please post some screenshots?

**Comment by teocomi** [comment]
Closing issue as no additional information was provided.
