### ISSUE TITLE
plug in for xbimxplorer

### ISSUE THREAD

**Issue by berndhahnebach** [teocomi/BCFier#34]
Hi Matteo ,
I have been searching for some OpenSource implementation for BCF. I was quite excited to find your BCFier. It is a great small tool. It really is a pitty it is in C#. Since I'm a Linux guy I do not know any C#, means contributing is rather difficault. Apart from this I do not develop on Windows but work (have to work) quite a lot on Windows too ...  Means BCFier may be of great use for me hopefully. 

On your repo here is a plug in for xbimxplorer. How does it works, or how do I install this? Do I have to compile something to get it running?

cheers bernd

**Comment by teocomi** [comment]
Hi @berndhahnebach I'd be curious to know what linux software you were planning to use BCF with! 

@CBenghi has developed the plugin for xbimxplorer, but it's not included in the installer, he can probably give you more information on how it works...

**Comment by CBenghi** [comment]
Thanks for your interest.
I have to document this properly. 
I'll do it during the weekend and come back to you.

**Comment by berndhahnebach** [comment]
hi guys thanks for your quick response. 
I'm starting to work with bcf. Since I'm on Linux and Windows I prefere software which runs on both systems. On FreeCAD forum we where discusing if it makes sense to to sone development in this regard. 

https://forum.freecadweb.org/viewtopic.php?f=23&t=22641

cheers bernd

**Comment by berndhahnebach** [comment]
> Thanks for your interest.
> I have to document this properly.
> I'll do it during the weekend and come back to you.

I have been playing around with BCF the whole day ....

BIMSight my favorite IFCsoftware does not support version 2, neither import nor expor (it seam they stop devlopment (timble bought tekla)). For solibri you need a special viewer to support bfc. BIM+ one of the plattform we use and able to handle bcf can not handle version 2 properly (no multiple screens) and and and. Eventually I did not found a proper solution to make or view BCF2 on my local machine inside a modell.

I would for sure give the xbim xplorer and BCFier a try even if it would be another viewer for ifc for me .. IFCQuery, IfcOpenShell, Solibri, BIMSight, it does not stop ... 

cheers bernd

I do not know anything about C# Why do you guys use this microsoft only developing languarge? What is the point ? C++ runs on any plattform, there are dozens compiler? What did MS that anybody uses this languarge ?

**Comment by CBenghi** [comment]
@berndhahnebach,
I've not had time to document the process properly, so I'll write here a few instructions for you.
Please note that the following steps are still unstable and I'm revising them in the coming weeks.

1. Setup Xplorer from http://docs.xbim.net/downloads/xbimxplorer.html
2. Once installed go to View/settings and then the Plugins tab.
3. Select "Development" in the plugin display filter.
4. Select the BCFier plugin and press "Download".
5. I think you need to select it again to press "Enable"
6. Probably select again to press the "Load" button.

These steps are only needed once, after that you should have the BCFier plugin enabled in the UI from the next restart.

Sorry the UI is so clumsy, will fix it soon.
Best,
Claudio

PS... automatic resource management and a great editor is the reason to go for c# 
But the mono project is doing very well, we are planning to port to mono in the long term for multiplatform.

**Comment by berndhahnebach** [comment]
tested the xbimexplorer and with BCFier plug in ...

In the regard of xbimexplorer, wow what a great tool, and it is OpenSource, but it is C# ... Such a pitty it does not run on Linux even it is OpenSource. Have you ever done a C# port with mono?

In the regard of the BCFier plug in. It opens the BCFier in xbimxplorer, thats great but it does not give any better user experience compared to the standalone BCFier. 

What I expected to work is to get the 3D-viewpoint out of the BCF and make xbimexplorer to use this viewpoint as well as mark or select the objects referenced in the BCF. Did I miss something in this regard. If this does work not work at the moment, it is planned to get this working?

cheers bernd

**Comment by CBenghi** [comment]
@berndhahnebach,
I'm not sure I understand the question, maybe you can open an issue on my page
https://github.com/CBenghi/BCFier/issues
with a bit more of detail.
Cheers
