### ISSUE TITLE
BCFier uninstallation

### ISSUE THREAD

**Issue by textilesense** [teocomi/BCFier#37]
Hi all. I tried to install BCFier, but when I opened a BCF file an error message popped up saying another application was using data. Definitely the add-in did not work. I unistalled it, by both cancelling BCFier folder from C/Program files/Autodesk/Revit2017/Add-ins/BCFier folder and then by uninstalling from Control Panel (I installed both the stand alone version and the Revit 2017 plug-in). When I re-opened Revit, the BCFier icon was still in the add-ins ribbon!!! Any way to get rid of the icon? Thanks.

**Comment by teocomi** [comment]
Hi, I'm sorry to hear that it's not working for you. Do you have additional information to help me debug the issue? Was Revit open when installing/uninstalling? Do you have admin rights on the machine? Any other versions of BCF/BCFier?

You can manually remove the Revit addin from:
C:\ProgramData\Autodesk\Revit\Addins\2017
ProgramData is a hidden folder.

**Comment by textilesense** [comment]
I found the hidden folder Program Data, I cancelled the BCFier folder, but now when I open Revit this message pops up: "the publisher of this add-in could not be verified. What do you want to do?". I chose "Do not load", so when I open a project the BCFier icon doesnt'appear, but when I close it and open again Revit, the message is shown again. Is there a way to fix it and then try to succesfully install BCFier stand alone and add-in modules?
Thank you so much!!

**Comment by teocomi** [comment]
If you have deleted the BCFier folder and .addin file in ProgramData\ there should be no other traces on your machine. Are you sure that error is referring to BCFier? Can you post an image?

**Comment by textilesense** [comment]
Ecco!!! Sono italiano anche io.


![screenshot 4](https://user-images.githubusercontent.com/6705150/27136505-66afd094-5113-11e7-8774-8a8049a9206c.jpg)

**Comment by textilesense** [comment]
Thanks for your help Matteo, I could fix everything. Unfortunately after cleaning up and then reinstalling BCFier, when I Try to open a BCF file, another message pops uo saying: "The process cannot access the file C:/Users/myname/AppData/Local/Temp/BCFier/a long alpha-numeric serial/another long alphanumeric serial/viewpoint.bcfv beacuse it is being used by another process". Is this maybe beacuse the AppData folder is a hidden one? I have no other applications open but Revit, in which I am using BCFier...
Thanks again.

**Comment by teocomi** [comment]
Closing this as you opened another one.
