### ISSUE TITLE
The process cannot access the file ... viewpoint.bcfv

### ISSUE THREAD

**Issue by textilesense** [teocomi/BCFier#38]
Hi  @teocomi   I have another issue.  When I Try to open a BCF file with BCFier, a message pops uo saying: "The process cannot access the file C:/Users/myname/AppData/Local/Temp/BCFier/a long alpha-numeric serial/another long alphanumeric serial/viewpoint.bcfv beacuse it is being used by another process". Is this maybe beacuse the AppData folder is a hidden one? I have no other applications open but Revit, in which I am using BCFier... Do I need perhaps to unhide the AppData folder?
Thanks.

**Comment by teocomi** [comment]
Hi, it's definitely not because of the hidden folder. Try to restart your pc and open the bcf again.

**Comment by textilesense** [comment]
I restarted my pc, but I still receive the message... This is with the stand alone version, but the situation is identical while trying to use the Revit add-in

**Comment by teocomi** [comment]
That is very unusual, can you please share the .bcfzip file you are trying to open? If the upload doesn't work here, send it to hello@teocomi.com

**Comment by teocomi** [comment]
Closing issue as no additional info was provided.
