### ISSUE TITLE
error on load of a bcf

### ISSUE THREAD

**Issue by berndhahnebach** [teocomi/BCFier#39]
I got an error opening a bcf saved with Allplan BIM services BIMPlus ... 

![screen](https://user-images.githubusercontent.com/6129869/27793475-78182e7c-5ffe-11e7-8d43-8e201b7e1e3c.jpg)

remove.txt
[testprj-testtask.bcfzip.txt](https://github.com/teocomi/BCFier/files/1119538/testprj-testtask.bcfzip.txt)

I can not tell whtat's wrong BCFier or Allplan ...

bernd

**Comment by teocomi** [comment]
Unfortunately their BCF file is not formatted correctly, according to the XML schema specifications boolean values have to be in lowercase: https://www.w3.org/TR/xmlschema-2/#boolean

```
 3.2.2.1 Lexical representation
  An instance of a datatype that is defined as ·boolean· can have the 
  following legal literals {true, false, 1, 0}. 

  3.2.2.2 Canonical representation
  The canonical representation for boolean is the set of 
  literals {true, false}. 
```

**Comment by berndhahnebach** [comment]
Thanks for pointing this out. I got in condact with development of BIM+

cheers bernd

**Comment by emrazek** [comment]
Problem is fixed

**Comment by berndhahnebach** [comment]
:-)  thanks, Eduard for giving feedback here and to me per email.
