### ISSUE TITLE
BCFier Revit addon might break GPL license

### ISSUE THREAD

**Issue by larsmoa** [teocomi/BCFier#4]
Note that the GPL license isn't suitable for writing addons for non-free programs (i.e. Revit). From http://www.gnu.org/licenses/gpl-faq.en.html#GPLPluginsInNF:

> Can I apply the GPL when writing a plug-in for a non-free program? (#GPLPluginsInNF)
> If the program uses fork and exec to invoke plug-ins, then the plug-ins are separate programs, so the license for the main program makes no requirements for them. So you can use the GPL for a plug-in, and there are no special requirements.
> 
> If the program dynamically links plug-ins, and they make function calls to each other and share data structures, we believe they form a single program, which must be treated as an extension of both the main program and the plug-ins. This means that combination of the GPL-covered plug-in with the non-free main program would violate the GPL. However, you can resolve that legal problem by adding an exception to your plug-in's license, giving permission to link it with the non-free main program.
> 
> See also the question I am writing free software that uses a non-free library.

I'm not familiar with the technical implementation of Revit addons, but I suspect that this restriction might be relevant for BCFier. However, it should be easy to add an exception as mentioned in the link above.

**Comment by teocomi** [comment]
Thanks a lot for pointing this out! I'll look into that ;)
