### ISSUE TITLE
using Revit viewer mode -> create snapshot not possible

### ISSUE THREAD

**Issue by SethMWu** [teocomi/BCFier#40]
Using Revit viewer for our structural engineers and project leads is a real handy option. 
However, use of BCFier is not supported in this mode :(  
When creating a view for an issue it immediately gets an error and doesn't produce a screenshot.
Can this be fixed? Or is creating a screenshot linked to locked options when in Viewer mode?

**Comment by teocomi** [comment]
Hi, I've just tried and I didn't get any error. What version are you using? Can you post a screenshot of the error?

![image](https://user-images.githubusercontent.com/2679513/28312218-4a0b8594-6baa-11e7-98ef-54d00c483e77.png)

**Comment by SethMWu** [comment]
Apologies. Retested it and now there doesn't appear to be an error. 
I think it occured because I updated a 2016 model to 2017 in Viewer mode. 
Then it gave errors when creating a screenshot, probably because it wanted to save to 2017 first :)
