### ISSUE TITLE
Doesn't work with Revit 2017

### ISSUE THREAD

**Issue by archjahz** [teocomi/BCFier#44]
Once I create a new issue or open an existing BCF file, Revit 2017 crashes.
I tried a blank project, an existing project, and the Revit sample architectural project and got the same result.

I tried it with Revit 2018 and it works fine.

Hope this gets fixed.

**Comment by teocomi** [comment]
Hi, just tried with 2017 and had no issues, maybe it's a compatibility problem with other addins? Can you try disabling them? Are you using the latest version 2.2.0?

**Comment by teocomi** [comment]
Closing as no answer was provided.
