### ISSUE TITLE
Building Problems

### ISSUE THREAD

**Issue by mgrzelak** [teocomi/BCFier#45]
Hi there,
I installed BCfier by installer. Then I tried to build module for Revit which worked fine. I then copied the BCfier.Revit.dll and BCFier.dll to C:\ProgramData\Autodesk\Revit\Addins\2016\Bcfier.Revit.

I did not change source code. Just tried if it works. Add-in opened but crashed after I clicked "New Bcf" button. I used Revit 2016, Windows 7, 64 bit.
Is it the proper procedure to update the build?

I did build the solution for Bcfier.win as well. (then copied .dll to proper location in program files). It works the same. It crashes after clicking "New Bcf".

Any idea what is wrong?

**Comment by teocomi** [comment]
Sorry the documentation is not up to date.
When you build the project you need to select the right build configuration and the dlls are automatically copied to the right destination (see inside the revit .csproj file for more info).
Your build probably crashes as you didn’t copy some required files.

**Comment by mgrzelak** [comment]
Matteo,
thank you for the fast response. I changed the build configuration and everything worked out well.
