### ISSUE TITLE
bcfier for Navisworks Compilation error

### ISSUE THREAD

**Issue by jazone** [teocomi/BCFier#51]
Hi @teocomi ,
I'm trying to compile the addin for Navisworks.
I'm getting this error :
'Components' does not contain definition for 'Any [...] (missing using or assembly?)' (translated from french)
Apparently no 'Any' methods are existing in the visinfo.cs file...
What can I do to fix this and install the addin in Navisworks?
Thanks in advance

**Comment by teocomi** [comment]
Hi, there is currently no release for Navis....
