### ISSUE TITLE
Future developing? when avaliable for Revit 2022 

### ISSUE THREAD

**Issue by heinrichboldt** [teocomi/BCFier#64]
Hi, 
have given a try, and love the tool. 
but since many month there is no update 

Will be further developing also for 2022 and maybe in few month for 2023?

BR
Heinrich Boldt

**Comment by teocomi** [comment]
Hey Heinrich,

Thanks for the suggestion, the project is not being actively developed but I'll give it a go at adding Revit 2022 this week!
BTW we're planning to add BCF like functionality to Speckle sometime soo, check it out: https://speckle.systems/

**Comment by heinrichboldt** [comment]
Hi
thanks for quick reply. 
Have heard about speckle.systems. but since we need to work in our project to solve reported issues this might be not usable for us

**Comment by teocomi** [comment]
Ok, this should do for now :)

https://github.com/teocomi/BCFier/releases/tag/v2.2.2.1
