### ISSUE TITLE
BCFier for REVIT 2023, 2024 ...

### ISSUE THREAD

**Issue by leiopar** [teocomi/BCFier#72]
Hello
Is a new version of BCFier planned for REVIT 2023, 2024 etc. ?

**Comment by teocomi** [comment]
Unfortunately, I'm not able to maintain this project anymore, but we're looking to add BCFier-like features to Speckle at some point.

https://speckle.systems/

**Comment by leiopar** [comment]
Can you tell to me what il the file to modify ?

**Comment by leiopar** [comment]
Hey ! Why thit topic is closed ???
there is no solution yet proposed !

**Comment by teocomi** [comment]
I closed it as I'm going to put this repo in Archive mode - I will not have time to review and approve new PRs unfortunately.
You need to create new build configs for other Revit versions & might need to change the code to work with new APIs https://github.com/teocomi/BCFier/blob/master/Bcfier.Revit/Bcfier.Revit.csproj
